import assert from "node:assert/strict";
import test from "node:test";
import {
  buildLocalPreview,
  detectGenomeFormat,
  hasProhibitedInference,
  validateGenomeBundle,
} from "../lib/ancestry.mjs";

test("detects VCF and consumer genotype formats", () => {
  assert.equal(detectGenomeFormat("sample.vcf", "##fileformat=VCFv4.2"), "vcf");
  assert.equal(
    detectGenomeFormat("raw.txt", "# This data file generated by 23andMe\nrs1\t1\t100\tAA"),
    "consumer-genotype",
  );
});

test("requires a complete PLINK bundle", () => {
  const incomplete = validateGenomeBundle([{ name: "sample.bed", size: 100 }]);
  assert.equal(incomplete.valid, false);

  const complete = validateGenomeBundle([
    { name: "sample.bed", size: 100 },
    { name: "sample.bim", size: 100 },
    { name: "sample.fam", size: 100 },
  ]);
  assert.equal(complete.valid, true);
});

test("local preview never invents personalised genetic conclusions", () => {
  const validation = validateGenomeBundle([{ name: "sample.vcf", size: 100 }]);
  const preview = buildLocalPreview(
    { displayName: "Asha", birthplace: "Hyderabad" },
    validation,
    { sampledLines: 20 },
  );
  assert.equal(preview.personalisedGeneticInference, false);
  assert.deepEqual(preview.conclusions, []);
  assert.match(preview.recentContext.warning, /not used to infer/i);
});

test("guardrail catches prohibited inference categories", () => {
  assert.equal(hasProhibitedInference({ result: "racial purity score" }), true);
  assert.equal(hasProhibitedInference({ result: "population affinity with uncertainty" }), false);
});
