// Original human-family atlas dataset.

const node = (config) => ({
  status: "living",
  type: "clade",
  uncertainty: "",
  traits: [],
  region: "Global",
  environment: "",
  accent: "#4ff0c4",
  ...config,
});

const edge = (source, target, kind = "branch") => ({ source, target, kind });

const humanNodes = [
  node({ id: "lca", x: 110, y: 520, label: "Human–chimp shared ancestor", scientific: "unknown ancestral populations", type: "root", status: "ancestral", time: "Roughly 8–6 million years ago", summary: "Humans did not descend from modern chimpanzees. Both lineages inherited traits from earlier shared populations.", evidence: "comparative genomics · fossils · molecular clocks", icon: "ape", trait: "A shared branch point, not a modern species", region: "Africa", environment: "Woodland mosaics", accent: "#62f5d1" }),
  node({ id: "pan", x: 390, y: 930, label: "Chimpanzees and bonobos", scientific: "Pan", type: "clade", status: "living", time: "Living sister lineage", summary: "Our closest living relatives are evolutionary cousins, not ancestors preserved unchanged from the past.", evidence: "genomes · anatomy · behavior", icon: "chimp", trait: "A living cousin branch", region: "Central and western Africa", environment: "Forests and woodland mosaics", accent: "#84d995" }),
  node({ id: "hominin-line", x: 390, y: 520, label: "Hominin lineage", scientific: "Hominini", type: "clade", status: "ancestral", time: "About 7 million years–present", summary: "The human-side branch after divergence from the ancestors of chimpanzees and bonobos.", evidence: "fossils · anatomy · genomes", icon: "footprints", trait: "Increasing commitment to bipedalism", region: "Africa", environment: "Woodlands and open habitats", accent: "#ff8d75" }),
  node({ id: "sahelanthropus", x: 690, y: 100, label: "Sahelanthropus", scientific: "Sahelanthropus tchadensis", type: "species", status: "extinct", time: "7–6 million years ago", summary: "An early possible hominin from Chad known mainly from cranial and dental remains.", evidence: "skull · teeth", icon: "skull-early", trait: "Possible early upright head posture", region: "Chad", environment: "Woodland near water", uncertainty: "Its placement within or near the hominin lineage is debated.", accent: "#e9a36e" }),
  node({ id: "orrorin", x: 690, y: 270, label: "Orrorin", scientific: "Orrorin tugenensis", type: "species", status: "extinct", time: "6.2–5.8 million years ago", summary: "Fragmentary Kenyan fossils combine climbing adaptations with femoral features interpreted as evidence of bipedal movement.", evidence: "femur · teeth · limb fragments", icon: "skull-early", trait: "Climbing + possible bipedalism", region: "Kenya", environment: "Woodland", uncertainty: "Its exact relationship to later hominins is uncertain.", accent: "#e5a271" }),
  node({ id: "ardipithecus", x: 690, y: 480, label: "Ardipithecus", scientific: "A. kadabba / A. ramidus", type: "clade", status: "extinct", time: "5.8–4.4 million years ago", summary: "Early hominins with a mosaic of arboreal traits and forms of upright movement unlike later australopiths.", evidence: "partial skeletons · teeth · habitat evidence", icon: "upright-ape", trait: "Mosaic locomotion", region: "Ethiopia", environment: "Woodland", accent: "#e89a70" }),
  node({ id: "australopiths", x: 980, y: 520, label: "Australopith radiation", scientific: "Australopithecus and close relatives", type: "clade", status: "extinct", time: "About 4.2–2 million years ago", summary: "A diverse radiation of habitual bipeds with relatively small brains—not a single straight ladder toward Homo.", evidence: "skeletons · footprints · teeth", icon: "footprints", trait: "Habitual bipedalism", region: "Eastern and southern Africa", environment: "Woodland–grassland mosaics", accent: "#df8b6c" }),
  node({ id: "anamensis", x: 1270, y: 90, label: "A. anamensis", scientific: "Australopithecus anamensis", type: "species", status: "extinct", time: "4.2–3.8 million years ago", summary: "One of the earliest named australopith species, with jaws and limb fossils indicating a mixture of ancestral and bipedal traits.", evidence: "jaws · teeth · limb fossils", icon: "skull-early", trait: "Early habitual bipedalism", region: "Kenya and Ethiopia", environment: "Woodlands near water", accent: "#d98d6b" }),
  node({ id: "afarensis", x: 1270, y: 250, label: "A. afarensis", scientific: "Australopithecus afarensis", type: "species", status: "extinct", time: "3.85–2.95 million years ago", summary: "Lucy’s species: clearly bipedal while retaining traits useful for climbing.", evidence: "Lucy · Laetoli footprints · many fossils", icon: "upright-ape", trait: "Bipedal feet + climbing shoulders", region: "Eastern Africa", environment: "Varied woodland and open habitats", accent: "#d98668" }),
  node({ id: "africanus", x: 1270, y: 410, label: "A. africanus", scientific: "Australopithecus africanus", type: "species", status: "extinct", time: "3.3–2.1 million years ago", summary: "A South African australopith known from numerous skulls and partial skeletons.", evidence: "skulls · teeth · postcranial fossils", icon: "skull-early", trait: "Small-brained biped", region: "South Africa", environment: "Woodland–grassland mosaics", accent: "#d47e68" }),
  node({ id: "sediba", x: 1270, y: 570, label: "A. sediba", scientific: "Australopithecus sediba", type: "species", status: "extinct", time: "About 1.98 million years ago", summary: "A striking mosaic of australopith-like and Homo-like features from South Africa.", evidence: "partial skeletons", icon: "skull-early", trait: "Anatomical mosaic", region: "South Africa", environment: "Woodland–grassland mosaic", uncertainty: "Its relationship to the origin of Homo is debated.", accent: "#cf7768" }),
  node({ id: "paranthropus", x: 1270, y: 820, label: "Robust australopiths", scientific: "Paranthropus", type: "clade", status: "extinct", time: "About 2.7–1.2 million years ago", summary: "A side radiation specialized for powerful chewing that overlapped in time with early Homo.", evidence: "skulls · jaws · teeth", icon: "skull-robust", trait: "Massive chewing apparatus", region: "Eastern and southern Africa", environment: "Varied habitats", accent: "#c99560" }),
  node({ id: "aethiopicus", x: 1550, y: 720, label: "P. aethiopicus", scientific: "Paranthropus aethiopicus", type: "species", status: "extinct", time: "2.7–2.3 million years ago", summary: "An early robust australopith from eastern Africa with a strongly built face and chewing system.", evidence: "skull · jaws · teeth", icon: "skull-robust", trait: "Early robust specialization", region: "Eastern Africa", environment: "Mixed habitats", accent: "#c08b5b" }),
  node({ id: "boisei", x: 1550, y: 870, label: "P. boisei", scientific: "Paranthropus boisei", type: "species", status: "extinct", time: "2.3–1.2 million years ago", summary: "An eastern African robust australopith with huge cheek teeth and powerful chewing adaptations.", evidence: "many skulls · jaws · teeth", icon: "skull-robust", trait: "Extreme chewing specialization", region: "Eastern Africa", environment: "Woodland and grassland mosaics", accent: "#b98358" }),
  node({ id: "robustus", x: 1550, y: 1020, label: "P. robustus", scientific: "Paranthropus robustus", type: "species", status: "extinct", time: "About 2–1.2 million years ago", summary: "A southern African robust australopith and evolutionary cousin of our lineage.", evidence: "skulls · jaws · teeth", icon: "skull-robust", trait: "Robust chewing system", region: "South Africa", environment: "Mixed habitats", accent: "#b77c58" }),
  node({ id: "homo-radiation", x: 1550, y: 450, label: "Genus Homo radiation", scientific: "Homo", type: "clade", status: "ancestral", time: "At least 2.4 million years–present", summary: "Multiple human species overlapped, dispersed, diverged, and sometimes exchanged genes.", evidence: "fossils · tools · archaeology · DNA", icon: "skull-homo", trait: "Brains, bodies, tools, and mobility diversify", region: "Africa, then Eurasia", environment: "Increasingly varied habitats", accent: "#f27c68" }),
  node({ id: "habilis", x: 1840, y: 90, label: "Homo habilis", scientific: "Homo habilis", type: "species", status: "extinct", time: "2.4–1.4 million years ago", summary: "An early Homo species associated with somewhat larger brains and early stone-tool traditions.", evidence: "skulls · hands · teeth · tools", icon: "skull-homo", trait: "Early Homo anatomy", region: "Eastern and southern Africa", environment: "Mixed habitats", accent: "#ea7568" }),
  node({ id: "rudolfensis", x: 1840, y: 240, label: "H. rudolfensis", scientific: "Homo rudolfensis", type: "species", status: "extinct", time: "About 1.9–1.8 million years ago", summary: "A debated early Homo species known mainly from cranial and dental fossils.", evidence: "skull · jaws · teeth", icon: "skull-homo", trait: "Distinctive early Homo face", region: "Eastern Africa", environment: "Lakeside and open habitats", uncertainty: "Species boundaries and relationships are debated.", accent: "#e06f66" }),
  node({ id: "erectus", x: 1840, y: 430, label: "Homo erectus", scientific: "Homo erectus", type: "species", status: "extinct", time: "1.89 million–about 110,000 years ago", summary: "A long-lived, widespread human lineage with modern-like body proportions and major dispersals beyond Africa.", evidence: "many fossils · tools · geography", icon: "walker", trait: "Long-distance walking and dispersal", region: "Africa and Eurasia", environment: "Highly varied", accent: "#dd6961" }),
  node({ id: "naledi", x: 1840, y: 590, label: "Homo naledi", scientific: "Homo naledi", type: "species", status: "extinct", time: "335,000–236,000 years ago", summary: "A South African species combining a small brain with a distinctive mosaic of hand, foot, shoulder, and pelvic traits.", evidence: "many individuals from cave deposits", icon: "skull-homo", trait: "Unexpected late-surviving mosaic", region: "South Africa", environment: "Cave deposits preserve the fossils", accent: "#d46462" }),
  node({ id: "middle-homo", x: 2140, y: 430, label: "Middle Pleistocene humans", scientific: "multiple populations", type: "clade", status: "ancestral", time: "Roughly 800,000–300,000 years ago", summary: "A complex set of populations near the ancestry of later humans; names and boundaries remain disputed.", evidence: "fossils · tools · proteins · ancient DNA", icon: "skull-homo", trait: "Regional populations diversify", region: "Africa and Eurasia", environment: "Cold and warm cycles", uncertainty: "Taxonomy is strongly debated.", accent: "#c95f62" }),
  node({ id: "island-homo", x: 2140, y: 780, label: "Island Homo branches", scientific: "H. floresiensis / H. luzonensis", type: "clade", status: "extinct", time: "Late Pleistocene", summary: "Island populations reveal that recent human diversity was far wider than a single species.", evidence: "skeletal fossils · island archaeology", icon: "island", trait: "Island evolution", region: "Southeast Asian islands", environment: "Island ecosystems", uncertainty: "Their deeper origins remain debated.", accent: "#c86f8b" }),
  node({ id: "antecessor", x: 2440, y: 130, label: "H. antecessor", scientific: "Homo antecessor", type: "species", status: "extinct", time: "About 850,000–770,000 years ago", summary: "An early European human population whose relationship to later lineages remains uncertain.", evidence: "fossils · proteins · archaeology", icon: "skull-homo", trait: "Early European population", region: "Spain", environment: "Temperate Europe", uncertainty: "Its placement is debated.", accent: "#be5a61" }),
  node({ id: "heidelbergensis", x: 2440, y: 350, label: "H. heidelbergensis group", scientific: "Homo heidelbergensis sensu lato", type: "clade", status: "extinct", time: "About 700,000–200,000 years ago", summary: "A traditional umbrella for Middle Pleistocene fossils; researchers disagree on how broadly to use the name.", evidence: "skulls · skeletons · tools", icon: "skull-homo", trait: "Large-bodied Middle Pleistocene humans", region: "Africa and Eurasia", environment: "Varied", uncertainty: "The name may combine several distinct populations.", accent: "#b95660" }),
  node({ id: "floresiensis", x: 2440, y: 730, label: "H. floresiensis", scientific: "Homo floresiensis", type: "species", status: "extinct", time: "About 100,000–50,000 years ago", summary: "A small-bodied human species from Flores, Indonesia, with a unique mixture of traits.", evidence: "partial skeletons · tools", icon: "island", trait: "Small-bodied island human", region: "Flores, Indonesia", environment: "Island forest", accent: "#b66786" }),
  node({ id: "luzonensis", x: 2440, y: 900, label: "H. luzonensis", scientific: "Homo luzonensis", type: "species", status: "extinct", time: "At least about 67,000–50,000 years ago", summary: "A distinct human species identified from teeth and small hand and foot bones in the Philippines.", evidence: "teeth · hand and foot bones", icon: "island", trait: "Distinct island anatomy", region: "Luzon, Philippines", environment: "Island tropics", accent: "#ad6481" }),
  node({ id: "neanderthal", x: 2740, y: 250, label: "Neanderthals", scientific: "Homo neanderthalensis", type: "species", status: "extinct", time: "About 400,000–40,000 years ago", summary: "A Eurasian human lineage with sophisticated behavior that interbred with Homo sapiens.", evidence: "fossils · archaeology · ancient DNA", icon: "skull-neanderthal", trait: "Cold-adapted bodies + complex culture", region: "Europe and western Asia", environment: "Glacial and interglacial Eurasia", accent: "#9d7bd8" }),
  node({ id: "denisovan", x: 2740, y: 460, label: "Denisovans", scientific: "Denisovan populations", type: "species", status: "extinct", time: "Middle–Late Pleistocene", summary: "An ancient human lineage recognized largely through DNA, with a growing but still sparse fossil record.", evidence: "ancient DNA · teeth · bone fragments", icon: "dna", trait: "A lineage first revealed by genomes", region: "Asia", environment: "From Siberia to high-altitude Asia", uncertainty: "Formal species naming remains unresolved.", accent: "#7f8fe8" }),
  node({ id: "sapiens-human", x: 2950, y: 650, label: "Homo sapiens", scientific: "Homo sapiens", type: "species", status: "living", time: "About 300,000 years–present", summary: "Our species emerged in Africa from structured populations, later dispersing and mixing with other human lineages.", evidence: "fossils · archaeology · ancient and modern DNA", icon: "human", trait: "Cumulative symbolic culture", region: "African origin; worldwide today", environment: "Every major biome", accent: "#ff6f70" }),
];

const humanEdges = [
  edge("lca", "pan"), edge("lca", "hominin-line"),
  edge("hominin-line", "sahelanthropus", "uncertain"), edge("hominin-line", "orrorin", "uncertain"), edge("hominin-line", "ardipithecus", "uncertain"), edge("hominin-line", "australopiths"),
  edge("australopiths", "anamensis", "uncertain"), edge("australopiths", "afarensis", "uncertain"), edge("australopiths", "africanus", "uncertain"), edge("australopiths", "sediba", "uncertain"), edge("australopiths", "paranthropus"), edge("australopiths", "homo-radiation", "uncertain"),
  edge("paranthropus", "aethiopicus", "uncertain"), edge("paranthropus", "boisei", "uncertain"), edge("paranthropus", "robustus", "uncertain"),
  edge("homo-radiation", "habilis", "uncertain"), edge("homo-radiation", "rudolfensis", "uncertain"), edge("homo-radiation", "erectus"), edge("homo-radiation", "naledi", "uncertain"),
  edge("erectus", "middle-homo", "uncertain"), edge("erectus", "island-homo", "uncertain"),
  edge("middle-homo", "antecessor", "uncertain"), edge("middle-homo", "heidelbergensis", "uncertain"), edge("middle-homo", "sapiens-human", "uncertain"),
  edge("island-homo", "floresiensis", "uncertain"), edge("island-homo", "luzonensis", "uncertain"),
  edge("heidelbergensis", "neanderthal", "uncertain"), edge("heidelbergensis", "denisovan", "uncertain"),
  edge("neanderthal", "sapiens-human", "geneFlow"), edge("denisovan", "sapiens-human", "geneFlow"),
];

export const HUMAN_VIEW = {
  id: "human",
  title: "Human Family",
  kicker: "fossils, branches, overlap, and gene flow",
  description: "Explore a branching and partly braided human history. Named fossil species are usually relatives, not proven direct grandparents.",
  canvas: { width: 3160, height: 1120 },
  initialViewport: { x: 0, y: 70, zoom: 1 },
  defaultNode: "lca",
  nodes: humanNodes,
  edges: humanEdges,
  eras: [
    { x: 0, width: 760, label: "7–4 million years", note: "the earliest possible hominins", tone: "forest" },
    { x: 760, width: 720, label: "4–2 million years", note: "australopith diversity", tone: "shore" },
    { x: 1480, width: 720, label: "2 million–800,000 years", note: "early Homo and dispersal", tone: "reef" },
    { x: 2200, width: 960, label: "800,000 years–present", note: "regional humans, DNA, and admixture", tone: "glacial" },
  ],
  journeys: [
    { id: "seven-million", label: "Seven million years", summary: "A cautious route through major populations and radiations.", steps: ["lca", "hominin-line", "ardipithecus", "australopiths", "homo-radiation", "erectus", "middle-homo", "sapiens-human"] },
    { id: "human-cousins", label: "Humans beside us", summary: "Several human lineages survived late enough to meet and mix.", steps: ["erectus", "middle-homo", "neanderthal", "denisovan", "sapiens-human"] },
    { id: "evolution-side-roads", label: "Side radiations", summary: "Robust chewers, cave populations, and island humans widened the experiment.", steps: ["paranthropus", "aethiopicus", "boisei", "robustus", "naledi", "island-homo", "floresiensis", "luzonensis"] },
  ],
};
